---
- name: Common | Update apt cache
  sudo: yes
  apt: update-cache=true
  tags: common

- name: Check dependencies
  sudo: yes
  apt: name=python-apt state=present

- name: Common | Update language
  sudo: yes
  apt: pkg=language-pack-en
  tags: common
